gamegearsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from orders.views import stripe_webhook_view
from products.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset_page.html'),
         name='reset_password'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/reset_password_sent_page.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_form.html'),
         name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_complete'),
]

# handler404 = page_not_found

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('order-create/', views.OrderCreateView.as_view(), name='create_order'),
    path('order-success/', views.SuccessView.as_view(), name='success_order'),
    path('order-canceled/', views.CanceledView.as_view(), name='canceled_order'),
    path('', views.OrderListView.as_view(), name='orders'),
    path('order/<int:pk>', views.OrderDetailView.as_view(), name='order')
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.LandingView.as_view(), name='landing'),
    path('goods/', views.product_list, name='products'),

    path('goods/page/<int:page>/', views.product_list, name='paginator_without_category'),
    path('catalog/<int:category_id>/', views.product_list, name='category'),
    path('catalog/<int:category_id>/page/<int:page>/', views.product_list, name='paginator'),

    path('aboutus/', views.AboutUsView.as_view(), name='aboutus'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),

    path('baskets/add/<int:product_id>/', views.basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', views.basket_remove, name='basket_remove'),

    path('goods/search/<int:page>/', views.search, name='search_view'),

    path('goods/<int:category_id>/sort/<int:page>/', views.sort, name='sort'),
    path('goods/sort/<int:page>/', views.sort, name='sort_no_category'),

    path('goods/product/<int:product_id>', views.product_page, name='product'),

    path('goods/review/<int:product_id>', views.review, name='review')
]

users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signin/', views.LoginUserView.as_view(), name='login'),
    path('signup/', views.RegistrationView.as_view(), name='register'),

    path('profile/<int:pk>/', login_required(views.ProfileView.as_view()), name='profile'),

    path('logout/', LogoutView.as_view(), name='logout'),

    path('verify/<str:email>/<uuid:code>/', views.EmailVerificationView.as_view(), name='email_verification'),
]

orders/models.py
from django.db import models

from products.models import Basket
from users.models import User


# Create your models here.
class Order(models.Model):
    '''Model for orders'''

    CREATED = 0
    PAID = 1
    ON_WAY = 2
    DELIVERED = 3
    STATUSES = (
        (CREATED, 'Created'),
        (PAID, 'Paid'),
        (ON_WAY, 'On the way'),
        (DELIVERED, 'Delivered'),
    )

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(max_length=256)
    address = models.CharField(max_length=256)
    basket_history = models.JSONField(default=dict)
    created = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(default=CREATED, choices=STATUSES)
    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Order id: {self.id}, User: {self.initiator}'

    def update_after_payment(self):
        baskets = Basket.objects.filter(user=self.initiator)
        self.status = self.PAID
        self.basket_history = {
            'purchased_items': [basket.de_json() for basket in baskets],
            'total_sum': float(baskets.total_sum()),
        }
        baskets.delete()
        self.save()

orders/forms.py
from django import forms

from orders.models import Order


class OrderForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'John'
    }), required=True)
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Todler'
    }), required=True)
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'you@example.com'
    }))
    address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'USA, some test street 2'
    }), required=True)

    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'address')

orders/views.py
from http import HTTPStatus

import stripe
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, DetailView, ListView, TemplateView

from gamegearsite import settings
from orders.forms import OrderForm
from orders.models import Order
from products.models import Basket

stripe.api_key = settings.STRIPE_SECRET_KEY

# Create your views here.
class SuccessView(TemplateView):
    template_name = 'orders/order_success_page.html'


class CanceledView(TemplateView):
    template_name = 'orders/canceled.html'


class OrderListView(ListView):
    template_name = 'orders/orders_page.html'
    queryset = Order.objects.all()
    ordering = ('-created')

    def get_queryset(self):
        queryset = super(OrderListView, self).get_queryset()
        return queryset.filter(initiator=self.request.user)


class OrderDetailView(DetailView):
    template_name = 'orders/order_item_page.html'
    model = Order


class OrderCreateView(CreateView):
    template_name = 'orders/order_page.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders:create_order')

    def post(self, request, *args, **kwargs):
        super(OrderCreateView, self).post(request, *args, **kwargs)
        baskets = Basket.objects.filter(user=self.request.user)

        checkout_session = stripe.checkout.Session.create(
            line_items=baskets.stripe_products(),
            mode='payment',
            success_url='{}{}'.format(settings.DOMAIN_NAME, reverse('orders:success_order')),
            cancel_url='{}{}'.format(settings.DOMAIN_NAME, reverse('orders:canceled_order')),
            metadata={
                'order_id': self.object.id,
            }
        )
        return HttpResponseRedirect(checkout_session.url, status=HTTPStatus.SEE_OTHER)

    def form_valid(self, form):
        form.instance.initiator = self.request.user
        return super(OrderCreateView, self).form_valid(form)

@csrf_exempt
def stripe_webhook_view(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return HttpResponse(status=400)

    # Handle the checkout.session.completed event
    if event['type'] == 'checkout.session.completed':
        # Retrieve the session. If you require line items in the response, you may include them by expanding line_items.
        session = stripe.checkout.Session.retrieve(
            event['data']['object']['id'],
            expand=['line_items'],
        )

        line_items = session.line_items
        # Fulfill the purchase...
        fulfill_order(session)

    # Passed signature verification
    return HttpResponse(status=200)


def fulfill_order(session):
    order_id = session.metadata['order_id']
    order = Order.objects.get(id=order_id)
    order.update_after_payment()

orders/templates/orders/canceled.html
<!DOCTYPE html>
<html>
<head>
  <title>Checkout canceled</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
  </section>
</body>
</html>

orders/templates/orders/order_item_page.html
{% extends 'products/basesite.html' %}
{% load static humanize %}

{% block header %}
    <title>Order Page</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'orders/css/orders_page.css' %}">
 {% endblock %}

{% block content %}
<div class="container">
    <section>
        <div class="container pt-5">
            <div class="text-center mt-5">
                <h1>Order №{{ object.id }}</h1>
                <div class="orders mt-5">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Title</th>
                            <th scope="col">Qty</th>
                            <th scope="col">Price</th>
                            <th scope="col">Sum</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in order.basket_history.purchased_items %}
                            <tr>
                            <th scope="row">
                                {{ item.product_name }}
                            </th>
                            <td>{{ item.quantity }}</td>
                            <td>{{ item.price|intcomma }} $</td>
                            <td>{{ item.sum|intcomma }} $</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <p class="float-right h4 mt-3">Summary {{ object.basket_history.total_sum|intcomma }} $</p>
                </div>
            </div>
        </div>
    </section>

</div>
{% endblock %}

orders/templates/orders/order_page.html
{% extends 'products/basesite.html' %}
{% load static humanize %}

{% block header %}
    <title>Order</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'orders/css/order_page.css' %}">
 {% endblock %}

{% block content %}
    <section>
        <!--    <div class="alert alert-warning text-center" role="alert">-->
        <!--        Пожалуйста, заполните адрес электронной почты.-->
        <!--    </div>-->
        <div class="container">
            <div class="py-5 text-center">
                <h1>Placing an order</h1>
            </div>
            <div class="row g-5">
                <div class="col-md-5 col-lg-4 order-md-last">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-primary">Shopping cart</span>
                        <span class="badge badge-primary badge-pill text-white">3</span>
                    </h4>
                    <ul class="list-group mb-3">
                        {% for basket in baskets %}
                            <li class="list-group-item d-flex justify-content-between lh-sm">
                                <div>
                                    <h6 class="my-0">{{ basket.product.name }}</h6>
                                    <small class="text-muted">{{ basket.quantity }} pcs.</small>
                                </div>
                                <span class="text-muted">{{ basket.sum|intcomma }} $</span>
                            </li>
                        {% endfor %}
                        <li class="list-group-item d-flex justify-content-between">
                            <span>Amount due</span>
                            <strong>{{ baskets.total_sum|intcomma }} $</strong>
                        </li>
                    </ul>
                </div>
                <div class="col-md-7 col-lg-8">
                    <h4 class="mb-3">Shipping address</h4>
                    <form action="{% url 'orders:create_order' %}" method="post">
                        {% csrf_token %}
                        <div class="row g-3">
                            <div class="col-sm-6">
                                <label for="{{ form.first_name.id_for_label }}" class="form-label">Name</label>
                                {{ form.first_name }}
                            </div>

                            <div class="col-sm-6">
                                <label for="{{ form.last_name.id_for_label }}" class="form-label">Surname</label>
                                {{ form.last_name }}
                            </div>

                            <div class="col-12 mt-3">
                                <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
                                {{ form.email }}
                            </div>

                            <div class="col-12 mt-3">
                                <label for="{{ form.address.id_for_label }}" class="form-label">Address</label>
                                {{ form.address }}
                            </div>

                        </div>

                        <hr class="my-4">

                        <button class="w-100 btn btn-primary btn-lg" type="submit">Continue</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

orders/templates/orders/order_success_page.html
{% extends 'users/baselogin.html' %}
{% load static %}

{% block title %}
    <title>Order Success</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'users/css/email_succes_page.css' %}">
{% endblock %}

{% block content %}
    <div class="email-container">
        <div class="main-text">
            <h1>Success</h1>
        </div>
        <div class="second-text">
            <h3>Order has been placed</h3>
            <button type="submit"><a href="{% url 'products:landing' %}">Main Page</a></button>
        </div>
    </div>
{% endblock %}

orders/templates/orders/orders_page.html
{% extends 'products/basesite.html' %}
{% load static humanize %}

{% block header %}
    <title>Orders</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'orders/css/orders_page.css' %}">
 {% endblock %}

{% block content %}
<div class="container">
    <section>
        <div class="container pt-5">
            <div class="text-center mt-5">
                <h1>Orders</h1>
                <div class="orders mt-5">
                    <table class="table">
                        <thead>
                        <tr class="table-light">
                            <th scope="col">#</th>
                            <th scope="col">Status</th>
                            <th scope="col">Created</th>
                            <th scope="col">Sum</th>
                            <th scope="col">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for order in object_list %}
                        <tr {% if order.status == 2 %} class="table-info" {% elif order.status == 3 %} class="table-success"{% endif %}>
                            <th scope="row">{{ order.id }}</th>
                            <td>{{ order.get_status_display }}</td>
                            <td>{{ order.created|naturaltime }}</td>
                            <td>{{ order.basket_history.total_sum|intcomma }} USD</td>
                            <td>
                                <a href="{% url 'orders:order' order.id %}">view</a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>

</div>
{% endblock %}