gamegearsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from orders.views import stripe_webhook_view
from products.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset_page.html'),
         name='reset_password'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/reset_password_sent_page.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_form.html'),
         name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_complete'),
]

# handler404 = page_not_found

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('order-create/', views.OrderCreateView.as_view(), name='create_order'),
    path('order-success/', views.SuccessView.as_view(), name='success_order'),
    path('order-canceled/', views.CanceledView.as_view(), name='canceled_order'),
    path('', views.OrderListView.as_view(), name='orders'),
    path('order/<int:pk>', views.OrderDetailView.as_view(), name='order')
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.LandingView.as_view(), name='landing'),
    path('goods/', views.product_list, name='products'),

    path('goods/page/<int:page>/', views.product_list, name='paginator_without_category'),
    path('catalog/<int:category_id>/', views.product_list, name='category'),
    path('catalog/<int:category_id>/page/<int:page>/', views.product_list, name='paginator'),

    path('aboutus/', views.AboutUsView.as_view(), name='aboutus'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),

    path('baskets/add/<int:product_id>/', views.basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', views.basket_remove, name='basket_remove'),

    path('goods/search/<int:page>/', views.search, name='search_view'),

    path('goods/<int:category_id>/sort/<int:page>/', views.sort, name='sort'),
    path('goods/sort/<int:page>/', views.sort, name='sort_no_category'),

    path('goods/product/<int:product_id>', views.product_page, name='product'),

    path('goods/review/<int:product_id>', views.review, name='review')
]

users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signin/', views.LoginUserView.as_view(), name='login'),
    path('signup/', views.RegistrationView.as_view(), name='register'),

    path('profile/<int:pk>/', login_required(views.ProfileView.as_view()), name='profile'),

    path('logout/', LogoutView.as_view(), name='logout'),

    path('verify/<str:email>/<uuid:code>/', views.EmailVerificationView.as_view(), name='email_verification'),
]

users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


# Create your models here.
class User(AbstractUser):
    '''User model'''

    image = models.ImageField(upload_to='users_images', null=True, blank=True)
    is_verified_email = models.BooleanField(default=False)


class EmailVerification(models.Model):
    '''EmailVerification to store data about user's email'''

    code = models.UUIDField(unique=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()

    def __str__(self):
        return f'EmailVerify obj for {self.user.email}'

    def send_verification_email(self):
        link = reverse('users:email_verification', kwargs={
            'email': self.user.email,
            'code': self.code
        })
        verification_link = f'{settings.DOMAIN_NAME}{link}'
        subject = f'Account confirmation for {self.user.username}'
        message = 'For account confirmation for {} follow the link {}'.format(
            self.user.email,
            verification_link
        )
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False,
        )

    def is_expired(self):
        return True if now() >= self.expiration else False

users/forms.py
import uuid
from datetime import timedelta

from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)
from django.utils.timezone import now

from users.models import EmailVerification, User

from .tasks import send_email_verification


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput())
    last_name = forms.CharField(widget=forms.TextInput())
    username = forms.CharField(widget=forms.TextInput())
    email = forms.CharField(widget=forms.EmailInput())
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=True)
        send_email_verification.delay(user.id)
        return user


class ProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4'
    }))
    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'custom-file-input',
    }), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'readonly': True
    }))
    email = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'readonly': True
    }))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image', 'username', 'email')

users/views.py
from django.contrib import auth, messages
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, UpdateView

from products.models import Basket
from users.forms import ProfileForm, UserLoginForm, UserRegisterForm
from users.models import EmailVerification, User


# Create your views here.
class LoginUserView(LoginView):
    template_name = 'users/login_page.html'
    form_class = UserLoginForm

    def form_invalid(self, form):
        messages.error(self.request, 'There was an error with username or password, check again !')
        return super().form_invalid(form)


class RegistrationView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register_page.html'
    success_url = reverse_lazy('products:landing')

    def form_valid(self, form):
        response = super().form_valid(form)
        auth.login(self.request, self.object, backend='django.contrib.auth.backends.ModelBackend')
        return response

    def form_invalid(self, form):
        messages.error(self.request, 'There was an error with username or password, check again !')
        return super().form_invalid(form)


class ProfileView(UpdateView):
    model = User
    form_class = ProfileForm
    template_name = 'users/profile_page.html'

    def get_success_url(self):
        return reverse_lazy('users:profile', args=(self.object.id,))

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class EmailVerificationView(TemplateView):
    template_name = 'users/email_succes_page.html'

    def get(self, request, *args, **kwargs):
        code = kwargs['code']
        user = User.objects.get(email=kwargs['email'])
        email_verification = EmailVerification.objects.filter(user=user, code=code)

        if email_verification.exists() and not email_verification.first().is_expired():
            user.is_verified_email = True
            user.save()
            return super(EmailVerificationView, self).get(request, *args, **kwargs)
        else:
            return redirect('products:landing')



# @login_required
# def profile(request):
#     if request.method == 'POST':
#         form = ProfileForm(instance=request.user, data=request.POST, files=request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('users:profile')
#     else:
#         form = ProfileForm(instance=request.user)
#
#     context = {
#         'form': form,
#         'baskets': Basket.objects.filter(user=request.user),
#     }
#
#     return render(request, 'users/profile_page.html', context)

# def logout(request):
#     auth.logout(request)
#     return redirect('products:landing')

# def login(request):
#     if request.method == 'POST':
#         form = UserLoginForm(request.POST)
#
#         # if form.is_valid():  # in prod, check the values
#
#         username = request.POST['username']
#         password = request.POST['password']
#         user = auth.authenticate(username=username, password=password)
#         if user:
#             auth.login(request, user)
#             return redirect('products:landing')
#         else:
#             messages.success(request, 'There was an error with username or password, check again !')
#             return redirect('users:login')
#     else:
#         form = UserLoginForm()
#
#     context = {
#         'form': form
#     }
#
#     return render(request, 'users/login.html', context)

# def register(request):
#     if request.method == 'POST':
#         form = UserRegisterForm(data=request.POST)
#         if form.is_valid():
#             form.save()
#             username = form.cleaned_data['username']
#             password = form.cleaned_data['password1']
#             user = auth.authenticate(username=username, password=password)
#             auth.login(request, user)
#             return redirect('products:landing')
#         else:
#             messages.success(request, 'There was an error with username or password, check again !')
#             return redirect('users:register')
#     else:
#         form = UserRegisterForm()
#
#     context = {
#         'form': form
#     }
#
#     return render(request, 'users/register_page.html', context)

users/templates/users/baselogin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %} {% endblock %}
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet">
    {% block css %} {% endblock %}
    <style>
        body::before {
            background-image: url('{% static 'products/images/background.jpg' %}');
        }
    </style>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

users/templates/users/email_succes_page.html
{% extends 'users/baselogin.html' %}
{% load static %}

{% block title %}
    <title>Email Success</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'users/css/email_succes_page.css' %}">
{% endblock %}

{% block content %}
    <div class="email-container">
        <div class="main-text">
            <h1>Congratulations !</h1>
        </div>
        <div class="second-text">
            <h3>Your email has been successfully verified</h3>
            <button type="submit"><a href="{% url 'products:landing' %}">Main Page</a></button>
        </div>
    </div>
{% endblock %}

users/templates/users/login_page.html
{% extends 'users/baselogin.html' %}
{% load static %}
{% load socialaccount %}

{% block title %}
    <title>Sign In</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'users/css/login_page.css' %}">
{% endblock %}

{% block content %}
    <div class="login-container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                    {{ message }}
                    <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
        <h2>Sign In</h2>
        <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            <div class="input-group">
                <label for="{{ form.username.id_for_label }}">Username</label>
            {{ form.username }}
        </div>
        <div class="input-group">
            <label for="{{ form.password.id_for_label }}">Password</label>
            {{ form.password }}
        </div>
        <div class="forgot-password">
            <a href="{% url 'reset_password' %}">Forgot your password?</a>
        </div>
        <button type="submit">Sign In</button>
        <div class="signup-text">
            <p class="centered-text">Don't have an account? <a href="{% url 'users:register' %}" class="signup-link">Sign Up</a></p>
        </div>
    </form>

    <!-- Додавання іконок та надпису "Забули пароль?" -->
    <div class="social-icons">
        <a href="{% provider_login_url 'facebook' %}" class="social-icon"><img src="{% static 'users/images/facebook.png' %}" alt="Facebook"></a>
        <a href="{% provider_login_url 'github' %}" class="social-icon"><img src="{% static 'users/images/github.png' %}" alt="GitHub"></a>
        <a href="{% provider_login_url 'google' %}" class="social-icon"><img src="{% static 'users/images/gmail.png' %}" alt="Google"></a>
    </div>

</div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'users/baselogin.html' %}
{% load static %}
{% load socialaccount %}

{% block title %}
    <title>Password reset</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'users/css/password_reset_done.css' %}">
{% endblock %}


{% block content %}
    <div class="login-container">
        <h2>Password reset complete</h2>
        <p>Your password has been set. You may go ahead and log in now.</p>
        <button type="submit"><a href="{% url 'users:login' %}">Log in</a></button>
    </div>
{% endblock %}

users/templates/users/password_reset_form.html
{% extends 'users/baselogin.html' %}
{% load static %}

{% block title %}
    <title>Reset Password</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'users/css/password_reset_form.css' %}">
{% endblock %}

{% block content %}
    <div class="login-container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                    {{ message }}
                    <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
        <h2>Reset Password</h2>
        <form method="post">
            {% csrf_token %}
            <div class="input-group">
                {{ form }}
            </div>
            <button type="submit">Reset Password</button>
        </form>

</div>
{% endblock %}

users/templates/users/password_reset_page.html
{% extends 'users/baselogin.html' %}
{% load static %}
{% load socialaccount %}

{% block title %}
    <title>Password reset</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'users/css/password_reset_page.css' %}">
{% endblock %}


{% block content %}
    <div class="login-container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                    {{ message }}
                    <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
        <h2>Password reset</h2>
        <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new
            one.</p>
        <form method="post">
            {% csrf_token %}
            <div class="input-group">
                {{ form }}
            </div>
            <button type="submit">Send Email</button>
        </form>
    </div>
{% endblock %}

users/templates/users/profile_page.html
{% extends 'products/basesite.html' %}
{% load static %}

{% block header %}
    <title>Profile</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'users/css/profile_page.css' %}">
 {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Profile</h4>
            <div class="col-lg-12 text-center">
                <img width="150" height="150"
                     src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'users/images/profileavatar.png' %}" {% endif %}
                     class="img-thumbnail">
            </div>
            <form action="{% url 'users:profile' user.id %}" method='post' enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Choose file</label>
                                {{ form.image }}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Name</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Surname</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Username</label>
                        {{ form.username }}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.email.id_for_label }}">Email</label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Save">
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-5">
            {% if baskets %}
            <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
                Shopping List <span class="badge badge-secondary badge-pill">3</span>
            </h4>
            {% for basket in baskets %}
                <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product.name }}</h5>
                    <p class="card-text">{{ basket.product.description|slice:":50"|add:"..." }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="basketID" type="number" class="form-control"
                                       value="{{ basket.quantity }}" min="0">
                            </div>
                            <div class="col-lg-4">{{ basket.sum }} $</div>
                            <div class="col-lg-4">
                                <a href="{% url 'products:basket_remove' basket.id %}">
                                    <img src="{% static 'users/images/trash-can.png' %}" alt="">
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            {% endfor %}
            <div class="card mb-3">
                <div class="card-footer">
                    <p class="float-left">Summary</p>
                    <h4 class="float-right">{{ baskets.total_sum }} $</h4>
                </div>
            </div>
            <a class="btn btn-success btn-lg float-right" href="{% url 'orders:create_order' %}">
                Make Order
            </a>
            {% else %}
                <h4 class="text-center">
                    Shopping List is empty
                </h4>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register_page.html
{% extends 'users/baselogin.html' %}
{% load static %}

{% block title %}
    <title>Sign Up</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'users/css/register_page.css' %}">
{% endblock %}

{% block content %}
<div class="login-container">
    {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                    {{ message }}
                    <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    <h2>Sign Up</h2>
    <form action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        <div class="input-group">
            <label for="{{ form.username.id_for_label }}">Username</label>
            {{ form.username }}
        </div>
        <div class="input-group">
            <label for="{{ form.first_name.id_for_label }}">Name</label>
            {{ form.first_name }}
        </div>
        <div class="input-group">
            <label for="{{ form.last_name.id_for_label }}">Surname</label>
            {{ form.last_name }}
        </div>
        <div class="input-group">
            <label for="{{ form.email.id_for_label }}">Email Address</label>
            {{ form.email }}
        </div>
        <div class="input-group">
            <label for="{{ form.password1.id_for_label }}">Password</label>
            {{ form.password1 }}
        </div>
        <div class="input-group">
            <label for="{{ form.password2.id_for_label }}">Password Confirmation</label>
            {{ form.password2 }}
            <p>Enter the same password as before, for verification</p>
        </div>
        <button type="submit">Sign Up</button>
        <div class="signin-text">
            <p class="centered-text">Already have an account? <a href="{% url 'users:login' %}" class="signin-link">Sign In</a></p>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/reset_password_sent_page.html
{% extends 'users/baselogin.html' %}
{% load static %}
{% load socialaccount %}

{% block title %}
    <title>Mail sent</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'users/css/reset_password_sent_page.css' %}">
{% endblock %}


{% block content %}
    <div class="login-container">
        <h2>Password reset sent</h2>
        <p>We've emailed you instructions for setting your password, if an account exists with the email you entered.
            You should receive them shortly</p>
        <p>If you don't receive an email, please make sure you've entered the address you registered with, and check
            your spam folder</p>
    </div>
{% endblock %}