gamegearsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from orders.views import stripe_webhook_view
from products.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset_page.html'),
         name='reset_password'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/reset_password_sent_page.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_form.html'),
         name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_complete'),
]

# handler404 = page_not_found

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('order-create/', views.OrderCreateView.as_view(), name='create_order'),
    path('order-success/', views.SuccessView.as_view(), name='success_order'),
    path('order-canceled/', views.CanceledView.as_view(), name='canceled_order'),
    path('', views.OrderListView.as_view(), name='orders'),
    path('order/<int:pk>', views.OrderDetailView.as_view(), name='order')
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.LandingView.as_view(), name='landing'),
    path('goods/', views.product_list, name='products'),

    path('goods/page/<int:page>/', views.product_list, name='paginator_without_category'),
    path('catalog/<int:category_id>/', views.product_list, name='category'),
    path('catalog/<int:category_id>/page/<int:page>/', views.product_list, name='paginator'),

    path('aboutus/', views.AboutUsView.as_view(), name='aboutus'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),

    path('baskets/add/<int:product_id>/', views.basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', views.basket_remove, name='basket_remove'),

    path('goods/search/<int:page>/', views.search, name='search_view'),

    path('goods/<int:category_id>/sort/<int:page>/', views.sort, name='sort'),
    path('goods/sort/<int:page>/', views.sort, name='sort_no_category'),

    path('goods/product/<int:product_id>', views.product_page, name='product'),

    path('goods/review/<int:product_id>', views.review, name='review')
]

users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signin/', views.LoginUserView.as_view(), name='login'),
    path('signup/', views.RegistrationView.as_view(), name='register'),

    path('profile/<int:pk>/', login_required(views.ProfileView.as_view()), name='profile'),

    path('logout/', LogoutView.as_view(), name='logout'),

    path('verify/<str:email>/<uuid:code>/', views.EmailVerificationView.as_view(), name='email_verification'),
]

products/models.py
import stripe
from django.db import models

from gamegearsite import settings
from users.models import User

stripe.api_key = settings.STRIPE_SECRET_KEY

# Create your models here.
class ProductCategory(models.Model):
    '''Model for category'''

    name = models.CharField(max_length=128)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    '''Model for our product'''

    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(decimal_places=1, max_digits=7)
    quantity = models.DecimalField(decimal_places=1, max_digits=7, default=0)
    image = models.ImageField(upload_to='product_images')
    stripe_product_price_id = models.CharField(max_length=128, null=True, blank=True)
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return f'Product: {self.name}, Category: {self.category}'

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.stripe_product_price_id:
            stripe_product_price = self.create_stripe_product_price()
            self.stripe_product_price_id = stripe_product_price['id']
        super(Product, self).save(force_insert=False, force_update=False, using=None, update_fields=None)

    def create_stripe_product_price(self):
        stripe_product = stripe.Product.create(name=self.name)
        stripe_product_price = stripe.Price.create(
            product=stripe_product['id'], unit_amount=round(self.price*100), currency='usd'
        )
        return stripe_product_price

class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def stripe_products(self):
        line_items = []
        for basket in self:
            item = {
                'price': basket.product.stripe_product_price_id,
                'quantity': basket.quantity
            }
            line_items.append(item)
        return line_items

class Basket(models.Model):
    '''Model for basket on the website'''

    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def __str__(self):
        return f'User: {self.user} Product: {self.product}'

    def sum(self):
        return self.product.price * self.quantity

    def de_json(self):
        baskets_item = {
            'product_name': self.product.name,
            'quantity': self.quantity,
            'price': float(self.product.price),
            'sum': float(self.sum())
        }
        return baskets_item


class Review(models.Model):
    '''Review model for reviews on the website'''

    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    comment = models.TextField(max_length=250)
    rate = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'User: {self.user}, Review product: {self.product}'

products/views.py
import re

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.cache import cache


from .models import Basket, Product, ProductCategory, Review

# Create your views here.
PER_PAGE = 6  # Constant for pagination

class LandingView(ListView):
    '''Landing page'''

    model = Product
    template_name = 'products/landing_page.html'

    def get_queryset(self):
        queryset = super(LandingView, self).get_queryset()
        return queryset.distinct('category')[:6]

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(LandingView, self).get_context_data()
        context['categories'] = ProductCategory.objects.all()
        return context


class AboutUsView(TemplateView):
    '''About Us page'''
    template_name = 'products/aboutus_page.html'


class ContactsView(TemplateView):
    '''Contacts page'''
    template_name = 'products/contacts_page.html'


@login_required
def basket_add(request, product_id):
    '''Logic of adding a product to basket'''

    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])

@login_required
def basket_remove(request, basket_id):
    '''Logic of removing a product to basket'''

    basket = Basket.objects.filter(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

def search_paginate(products, sort_option, page):
    '''Helper function to get paginate pages'''

    sorting_options = {
        'alphabet': 'name',
        'low-high': 'price',
        'high-low': '-price',
    }

    sort_field = sorting_options.get(sort_option)
    if sort_field:
        products = products.order_by(sort_field)

    paginator = Paginator(products, PER_PAGE)
    products_paginator = paginator.page(page)

    return products_paginator


def product_list(request, category_id=None, page=1):
    '''Product list page'''

    products = Product.objects.filter(category_id=category_id) if category_id else Product.objects.all()
    sort_option = request.GET.get('sorting-products')

    context = {
        'categories': ProductCategory.objects.all(),
        'products': search_paginate(products, sort_option, page),
        'category_id': category_id,
        'current_sorting_option': request.GET.get('sorting-products', 'default'),
    }

    return render(request, 'products/products_page.html', context)

def sort(request, category_id=None, page=1):
    products = Product.objects.filter(category_id=category_id) if category_id else Product.objects.all()
    sort_option = request.GET.get('sorting-products')
    search_query = request.GET.get('search', '')

    if search_query:
        products = products.filter(name__icontains=search_query)

    context = {
        'categories': ProductCategory.objects.all(),
        'products': search_paginate(products, sort_option, page),
        'category_id': category_id,
        'page': page,
        'search_query': search_query,
        'current_sorting_option': request.GET.get('sorting-products', 'default'),
    }

    return render(request, 'products/products_page.html', context)


def search(request, page=1):
    '''Logic of search'''

    search_query = request.GET.get('search')
    sort_option = request.GET.get('sorting-products')

    if search_query is None:
        products = Product.objects.all()
    else:
        products = Product.objects.filter(name__icontains=search_query)

    context = {
        'categories': ProductCategory.objects.all(),
        'products': search_paginate(products, sort_option, page),
        'search_query': search_query,
        'current_sorting_option': sort_option,
        'flag_search': True
    }

    return render(request, 'products/products_page.html', context)


@receiver(post_save, sender=Product)
def clear_cache(sender, **kwargs):
    cache.clear()

@receiver(post_save, sender=Review)
def clear_cache(sender, **kwargs):
    cache.clear()

def cache_key_prefixer(request):
    key = 'product_page:' + request.path
    sanitized_key = re.sub(r'[^a-zA-Z0-9-_:./]', '_', key)
    return sanitized_key

@cache_page(60*5, key_prefix=cache_key_prefixer)  # Cache for 5 minutes
def product_page(request, product_id):
    '''Product page'''
    product = Product.objects.get(id=product_id)
    reviews = Review.objects.filter(product=product)

    context = {
        'categories': ProductCategory.objects.all(),
        'product': product,
        'reviews': reviews
    }

    return render(request, 'products/product_page.html', context)

def page_not_found(request):
    return render(request, 'products/page_not_found.html')


def review(request, product_id):
    if request.method == 'GET':
        product = Product.objects.get(id=product_id)

        comment = request.GET.get('review')
        rate = request.GET.get('rating')
        user = request.user

        if not comment or not rate:
            messages.error(request, 'Both rating and review text are required.')
            return HttpResponseRedirect(request.META['HTTP_REFERER'])

        Review(user=user, product=product, comment=comment, rate=rate).save()

        return HttpResponseRedirect(request.META['HTTP_REFERER'])


# class ProductsView(ListView):
#     model = Product
#     template_name = 'products/products_page.html'
#     paginate_by = 6
#
#     def get_queryset(self):
#         queryset = super().get_queryset()
#         category_id = self.kwargs.get('category_id')
#         search_query = self.request.GET.get('search')
#         sort_option = self.request.GET.get('sorting-products')
#
#         if category_id:
#             queryset = queryset.filter(category_id=category_id)
#         if search_query:
#             queryset = queryset.filter(name__icontains=search_query)
#
#         sorting_options = {
#             'alphabet': 'name',
#             'low-high': 'price',
#             'high-low': '-price'
#         }
#
#         if sort_option in sorting_options:
#             sort_field = sorting_options[sort_option]
#             queryset = queryset.order_by(sort_field)
#
#         return queryset
#
#     def get_context_data(self, *, object_list=None, **kwargs):
#         context = super().get_context_data()
#         context['categories'] = ProductCategory.objects.all()
#         context['category_id'] = self.kwargs.get('category_id')
#         context['search_query'] = self.request.GET.get('search')
#         context['sort_option'] = self.request.GET.get('sorting-products')
#         return context
#
#     def get_paginate_by(self, queryset):
#         if self.request.GET.get('search') is not None or self.request.GET.get('sorting-products') is not None:
#             return None
#         return super().get_paginate_by(queryset)

products/templates/products/aboutus_page.html
{% extends 'products/basesite.html' %}
{% load static %}

{% block header %}
    <title>About Us</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'products/css/aboutus_page.css' %}">
 {% endblock %}

{% block content %}
<div class="container">
    <div class="container about-us">
        <h2>About Us</h2>
        <p class="about-us-text">
            We are a gaming technology company founded in 2005. We specialize in providing top-notch gaming gear to
            gamers around the world. With hundreds of satisfied customers, we are committed to delivering the best
            gaming experience.
        </p>
    </div>
</div>
{% endblock %}

products/templates/products/basesite.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block header %} {% endblock %}
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet">
    {% block css %} {% endblock %}
    <style>
        body::before {
            background-image: url('{% static 'products/images/background.jpg' %}');
        }
        {% block style %} {% endblock %}
    </style>
</head>
<body>

<header>
    <img src="{% static 'products/images/logo_gamegearpng.png' %}" alt="Game Gear Logo" class="header-image">
</header>
<nav>
    <div class="left-side">
        <a class="nav-button" href="{% url 'products:landing' %}">Home</a>
        <a class="nav-button" href="{% url 'products:products' %}">Products</a>
        <a class="nav-button" href="{% url 'products:aboutus' %}">About Us</a>
        <a class="nav-button" href="{% url 'products:contacts' %}">Contact</a>
    </div>
    <div class="right-side">
        <form class="nav-search" action="{% url 'products:search_view' 1 %}" method="get">
            <input type="search" name="search" placeholder="Search">
            <button type="submit"><img src="{% static 'products/images/search.png' %}" alt="Search"></button>
        </form>
        {% if user.is_authenticated %}
            <a class="nav-button sign-btn" href="{% url 'users:logout' %}">Logout</a>
            <a class="nav-button sign-btn" href="{% url 'orders:orders' %}">Orders</a>
        {% else %}
            <a class="nav-button sign-btn" href="{% url 'users:login' %}">Sign In</a>
            <a class="nav-button sign-btn" href="{% url 'users:register' %}">Sign Up</a>
        {% endif %}
        <a class="nav-button"
           href="{% if user.is_authenticated %} {% url 'users:profile' user.id %} {% else %} {% url 'users:login' %} {% endif %}"><img
                src="{% static 'products/images/shopping-cart.png' %}" alt="" class="shopping-cart"></a>
    </div>
</nav>

{% block content %} {% endblock %}

<div class="wrapper">
    <footer class="footer">
        <div class="footer-content">
            <p>&copy; 2023 Online Store Pet Project</p>
            <a href="https://www.linkedin.com/in/vlad-musaelyan-5966a1278/">
                <img src="{% static 'products/images/footer/icon_link.png' %}" alt="">
            </a>
            <a href="https://github.com/drakoRRR">
                <img src="{% static 'products/images/footer/icon_github.png' %}" alt="">
            </a>
        </div>
    </footer>
</div>

</body>
</html>

products/templates/products/border_menu.html
{% load cache %}

<div class="border-menu">
{% cache 3600 categories %}
    {% for category in categories %}
        <a href="{% url 'products:category' category.id %}">{{ category.name }}</a>
    {% endfor %}
{% endcache %}
</div>

products/templates/products/contacts_page.html
{% extends 'products/basesite.html' %}
{% load static %}

{% block header %}
    <title>Contacts</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'products/css/contacts_page.css' %}">
 {% endblock %}

{% block content %}
<div class="container">
    <div class="container contacts">
        <img src="{% static 'products/images/logo_gamegearpng.png' %}" alt="Company Logo" class="company-logo">
        <h1>Game Gear Shop</h1>
        <p>Since 2005</p>
        <p>Phone: +1 (123) 456-7890</p>
        <p>Phone: +1 (987) 654-3210</p>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3152.524727731841!2d-122.08408118461937!3d37.42199997982492!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808fbb4d7f31766d%3A0xe8d46ba20d50f7eb!2sGoogle%20LLC!5e0!3m2!1sen!2sus!4v1631698400049!5m2!1sen!2sus" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
    </div>
</div>
{% endblock %}

products/templates/products/landing_page.html
{% extends 'products/basesite.html' %}
{% load static humanize %}

{% block header %}
    <title>Gaming Device Shop</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'products/css/landing_page.css' %}">
 {% endblock %}

{% block content %}
    <div class="slideshow-container">
        <div class="mySlides fade">
            <img src="{% static 'products/images/promo/promo1.jpg' %}" alt="Slide 1">
        </div>

        <div class="mySlides fade">
            <img src="{% static 'products/images/promo/promo2.jpg' %}" alt="Slide 2">
        </div>

        <div class="mySlides fade">
            <img src="{% static 'products/images/promo/promo3.jpg' %}" alt="Slide 3">
        </div>

    </div>

    <div class="container">
        {% include 'products/border_menu.html' %}

        <div class="products">
            {% for product in object_list %}
                <div class="product">
                    <a href="{% url 'products:product' product.id %}">
                        <div class="product-image">
                            <img src="{{ product.image.url }}" alt="Gaming Mouse">
                        </div>
                    </a>
                    <h2>{{ product.name }}</h2>
                    <p>{{ product.description|slice:":85"|add:"..." }}</p>
                    <p class="product-price">${{ product.price|intcomma }}</p>
                    <button class="add-to-cart-button"><a href="{% url 'products:basket_add' product.id %}"
                                                          style="text-decoration: none; color: inherit;">Add to
                        Cart</a></button>
                </div>
            {% endfor %}
        </div>
    </div>


    <script>
        let slideIndex = 0;
        showSlides();

    function showSlides() {
        let slides = document.getElementsByClassName("mySlides");

        for (let i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }

        slideIndex++;

        if (slideIndex > slides.length) {
            slideIndex = 1;
        }

        slides[slideIndex - 1].style.display = "block";
        setTimeout(showSlides, 3000);
    }
</script>



{% endblock %}

products/templates/products/page_not_found.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gaming Device Shop</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'products/css/page_not_found.css' %}">
</head>
<body>
    <img src="{% static 'products/images/404.png' %}" alt="">
    <h1>Error</h1>
    <h2>Page not found...</h2>
    <button><a href="{% url 'products:landing' %}">Main Page</a></button>
</body>
</html>

products/templates/products/product_page.html
{% extends 'products/basesite.html' %}
{% load static humanize %}

{% block header %}
    <title>Product Page</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'products/css/product_page.css' %}">
{% endblock %}

{% block style %}
    .rating label {
        background-image: url({% static 'products/images/star_unfilled.png' %});
    }

    .rating input[type="radio"]:checked ~ label {
    background-image: url({% static 'products/images/star_filled.png' %});
    }

    .rating input:checked + label ~ label {
    background-image: url({% static 'products/images/star_unfilled.png' %});
    }
{% endblock %}

{% block content %}
<div class="container">

    {% include 'products/border_menu.html' %}

    <main class="container-main">
        <div class="left-column">
            <img src="{{ product.image.url }}" alt="Product Image">
        </div>
        <div class="right-column">
            <div class="product-description">
                <h1>{{ product.name }}</h1>
                <span>{{ product.category }}</span>
                <p>{{ product.description }}</p>
            </div>
            <div class="product-price">
                <span>{{ product.price|intcomma }}$</span>
                <a href="{% url 'products:basket_add' product.id %}" class="cart-btn">Add to cart</a>
            </div>
            <div class="user-reviews">
                <h2>User Reviews</h2>
                {% for review in reviews %}
                    <div class="single-review"
                         style="padding: 20px; border: 1px solid #ddd; border-radius: 5px;">
                        <h3 style="font-size: 24px; color: #333;">{{ review.user.username }}</h3>
                        <p style="font-size: 14px; color: #666;">{{ review.created_at }}</p>
                        {% if not review.rate or not review.comment %}
                            {% for message in messages %}
                                <div class="alert alert-danger" role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <p style="font-size: 18px; color: #333;">
                            {% if review.rate == 1 %} <span>★</span>☆☆☆☆ {% endif %}
                            {% if review.rate == 2 %} <span>★★</span>☆☆☆ {% endif %}
                            {% if review.rate == 3 %} <span>★★★</span>☆☆ {% endif %}
                            {% if review.rate == 4 %} <span>★★★★</span>☆ {% endif %}
                            {% if review.rate == 5 %} <span>★★★★★</span> {% endif %}
                        </p>
                        <p style="font-size: 16px; color: #333;">{{ review.comment }}</p>
                    </div>
                {% endfor %}
            </div>

            <!-- Product Reviews -->
            <div class="product-reviews">
                <h2>Leave a Review</h2>
                <!-- Review Form -->
                <form class="review-form" method="GET" action="{% url 'products:review' product.id %}">
                    <label for="rating">Rating:</label>
                    <div class="rating" id="rating">
                        <input type="radio" id="star5" name="rating" value="5">
                        <label for="star5" title="5 stars"></label>
                        <input type="radio" id="star4" name="rating" value="4">
                        <label for="star4" title="4 stars"></label>
                        <input type="radio" id="star3" name="rating" value="3">
                        <label for="star3" title="3 stars"></label>
                        <input type="radio" id="star2" name="rating" value="2">
                        <label for="star2" title="2 stars"></label>
                        <input type="radio" id="star1" name="rating" value="1">
                        <label for="star1" title="1 star"></label>
                    </div>

                    <label for="review">Your Review:</label><br>
                    <textarea id="review" name="review"></textarea><br>

                    <input type="submit" value="Submit">
                </form>
            </div>
        </div>
    </main>
</div>
{% endblock %}

products/templates/products/products_page.html
{% extends 'products/basesite.html' %}
{% load static humanize %}

{% block header %}
    <title>Products</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'products/css/products_page.css' %}">
{% endblock %}

{% block content %}
    <div class="search-text">
        {% if search_query %}<h1>Results for: {{ search_query }}</h1>{% endif %}
        <div class="order-options">
            <label for="order">Order by:</label>
            <form action="{% if category_id %} {% url 'products:sort' category_id 1 %} {% else %} {% url 'products:sort_no_category' 1 %} {% endif %}"
                  method="GET">
                <select id="order" name="sorting-products">
                    <option value="alphabet">Alphabet</option>
                    <option value="low-high">Low to High</option>
                    <option value="high-low">High to Low</option>
                </select>

                <!-- Include the search query as a hidden input field -->
                <input type="hidden" name="search" value="{{ search_query }}">

                <button type="submit">Sort</button>
            </form>
        </div>
    </div>
    <div class="container">
        {% include 'products/border_menu.html' %}
        <div class="products">
        {% for product in products %}
            <div class="product">
                <a href="{% url 'products:product' product.id %}">
                    <div class="product-image">
                        <img src="{{ product.image.url }}" alt="Gaming Mouse">
                    </div>
                </a>
                <h2>{{ product.name }}</h2>
                <p>{{ product.description|slice:":85"|add:"..." }}</p>
                <p class="product-price">${{ product.price|intcomma }}</p>
                <button class="add-to-cart-button"><a href="{% url 'products:basket_add' product.id %}" style="text-decoration: none; color: inherit;">Add to
                    Cart</a></button>
            </div>
        {% endfor %}
    </div>
</div>

    {% if request.GET.search %}
        <div class="pagination">
            <ul>
                <li class="{% if products.has_previous %} active {% else %} disabled {% endif %}">
                    <a href="{% if products.has_previous %} {% url 'products:search_view' products.previous_page_number %}?search={{ search_query }}&sorting-products={{ current_sorting_option }} {% else %} # {% endif %}">Previous</a>
                </li>
                {% for page in products.paginator.page_range %}
                    <li>
                        <a href="{% url 'products:search_view' page %}?search={{ search_query }}&sorting-products={{ current_sorting_option }}">{{ page }}</a>
                    </li>
                {% endfor %}
                <li class="{% if products.has_next %} active {% else %} disabled {% endif %}">
                    <a href="{% if products.has_next %} {% url 'products:search_view' products.next_page_number %}?search={{ search_query }}&sorting-products={{ current_sorting_option }} {% else %} # {% endif %}">Next</a>
                </li>
            </ul>
        </div>
    {% else %}
        <div class="pagination">
            <ul>
                <li class="{% if products.has_previous %} active {% else %} disabled {% endif %}">
                    <a href="{% if products.has_previous %}
                   {% if category_id %}
                       {% url 'products:paginator' category_id products.previous_page_number %}?sorting-products={{ current_sorting_option }}
                   {% else %}
                       {% url 'products:paginator_without_category' products.previous_page_number %}?sorting-products={{ current_sorting_option }}
                   {% endif %}
               {% else %} #
               {% endif %}">Previous</a>
                </li>
                {% for page in products.paginator.page_range %}
                    <li>
                        <a href="{% if category_id %}
                       {% url 'products:paginator' category_id page %}?sorting-products={{ current_sorting_option }}
                   {% else %}
                       {% url 'products:paginator_without_category' page %}?sorting-products={{ current_sorting_option }}
                   {% endif %}
                   ">{{ page }}</a>
                    </li>
                {% endfor %}
                <li class="{% if products.has_next %} active {% else %} disabled {% endif %}">
                    <a href="{% if products.has_next %}
                   {% if category_id %}
                       {% url 'products:paginator' category_id products.next_page_number %}?sorting-products={{ current_sorting_option }}
                   {% else %}
                       {% url 'products:paginator_without_category' products.next_page_number %}?sorting-products={{ current_sorting_option }}
                   {% endif %}
               {% else %} #
               {% endif %}">Next</a>
                </li>
            </ul>
        </div>
    {% endif %}

{% endblock %}